---
- name: Configure webserver with nginx
  hosts: webservers
  sudo: True
  tasks:
    - name: Check if Package is installed
      patch: >
        src=/tmp/fix_bug_1234.patch
        dst=/usr/share/pyshared/nova/manager.py     
      register: patch_result
      failed_when: patch_result.stdout.find('Reversed (or previously applied) patch detected') != -1
    
      

